### ISSUE TITLE
Placeholder Text Missing

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/spark-screen-builder#151]
Placeholder text isn't being rendered in the design mode.

![image](https://user-images.githubusercontent.com/535300/56586536-beabb500-6594-11e9-912b-3ba18acfe086.png)

**Comment by chipit24** [comment]
@velkymx Should this type of interpolation only work for the `FormText` component (the one in the screenshot above?

**Comment by velkymx** [comment]
FormText and RichText
