### ISSUE TITLE
BUG: Record List using Select Element - Default option doesn't end up in data payload

### ISSUE THREAD

**Issue by ssshake** [ProcessMaker/spark-screen-builder#166]
- Create select with 2 options
- add a record
- Do not change the drop down
- Save record
- Item will not show up in data

Taylor says "May be bug in vue-form-elements not in screen builder"

**Comment by velkymx** [comment]
Applies to all selects.

https://www.dropbox.com/s/wx1vdnag4324pll/select-default-value.mov?dl=0

**Comment by velkymx** [comment]
We've patched this in form-elements. 

https://github.com/ProcessMaker/vue-form-elements/issues/37
