### ISSUE TITLE
Preview Inspector is not the same width as Design Inspector

### ISSUE THREAD

**Issue by ssshake** [ProcessMaker/spark-screen-builder#172]
These should both use the same classes 

![image](https://user-images.githubusercontent.com/1675868/57803210-d9052880-7725-11e9-8925-b0a07cca66b5.png)

**Comment by velkymx** [comment]
![inspector-sidebyside](https://user-images.githubusercontent.com/535300/57805604-11027080-7712-11e9-891b-9194a86733b2.png)

**Comment by velkymx** [comment]
They should look the same...
