### ISSUE TITLE
Bottom border is missing on drag

### ISSUE THREAD

**Issue by ssshake** [ProcessMaker/spark-screen-builder#174]
![image](https://user-images.githubusercontent.com/1675868/57806867-0bb31f00-772e-11e9-84b7-e1b53d70f074.png)

**Comment by chipit24** [comment]
For clarification: This happens for the drag preview or "ghost" when dragging a new element from the controls list onto the form; there are no issues with dragging to re-order elements already in the form. 

This seems to happen with all controls, not just `Select`, and the border _does_ appear if it's the last element in the form (dragged to the bottom of the list).
