### ISSUE TITLE
Bug in Filter Controls

### ISSUE THREAD

**Issue by caleeli** [ProcessMaker/spark-screen-builder#179]
The correct control is not loaded after using the controls filter

![SearchScreenBuilder](https://user-images.githubusercontent.com/8028650/57538631-d6b26100-7316-11e9-9a0f-9a7425dcca0b.gif)

**Comment by tuantruong625** [comment]
This bug is fixed in #164
![filter-control](https://user-images.githubusercontent.com/26545455/57873702-f0531d00-77dc-11e9-940d-99c1c02791e6.gif)

**Comment by ssshake** [comment]
@velkymx @caleeli we've already fixed and tested this so I think we have to have more information such as what branch / commit was this issue found on.

**Comment by velkymx** [comment]
This is resolved in develop
