### ISSUE TITLE
Records List Not working

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/spark-screen-builder#183]
![image](https://user-images.githubusercontent.com/535300/57880326-4fac2f80-77d3-11e9-8de2-b9041f067dd4.png)

**Comment by ssshake** [comment]
@velkymx is this still happening or was this fixed?

**Comment by ssshake** [comment]
I get different error. Continuing to look

![image](https://user-images.githubusercontent.com/1675868/57936641-55b51580-7892-11e9-9b27-38fbc879281d.png)
