### ISSUE TITLE
Display Screens Preview Broken

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/spark-screen-builder#187]
![image](https://user-images.githubusercontent.com/535300/57932295-715af480-786f-11e9-822f-f8316a480fd5.png)

![image](https://user-images.githubusercontent.com/535300/57932289-6c964080-786f-11e9-9734-513ddf8033ee.png)

**Comment by ssshake** [comment]
I'm seeing other errors too. This is stuff that was fixed in Rob's PR that got reverted. We are looking at bringing the relevant changes back in.

![image](https://user-images.githubusercontent.com/1675868/57937464-ffe16d00-7893-11e9-9967-3d489f22c36c.png)

**Comment by ssshake** [comment]
Check if bringing in vue form renderer should auto load these components. Taylor wants to know
