### ISSUE TITLE
Screen Pages Cannot be Deleted

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/spark-screen-builder#189]
After you create additional pages, you cannot remove any of them.

**Comment by chipit24** [comment]
I could not re-produce this in standalone, but was able to reproduce it in spark after some testing:

1. Create a new screen.
2. Add a page to the screen, save it, and return to the screens page.
3. Click to edit the screen, and attempt to delete the page you added. The following error appears and the page is not deleted:
```
[Vue warn]: Error in v-on handler: "TypeError: Cannot read property 'runtime' of undefined"

found in

---> <BModal>
       <VueFormBuilder>
         <ScreenBuilder> at resources/js/processes/screen-builder/screen.vue
           <Root>
```

You are still able to delete your initial, default page.
