### ISSUE TITLE
Multi-Column / Table not rendering in Spark

### ISSUE THREAD

**Issue by ssshake** [ProcessMaker/spark-screen-builder#214]
Screen is configured in Design tab like so:

![image](https://user-images.githubusercontent.com/1675868/58577590-cfdf8580-8214-11e9-8b4a-1047921d7377.png)

Preview is blank, I hope that is due to the known issue being worked on: https://github.com/ProcessMaker/spark-screen-builder/issues/200

![image](https://user-images.githubusercontent.com/1675868/58577602-d3730c80-8214-11e9-87ae-67caeb605177.png)

Rendering the screen in spark is not showing the multi-column, just the Text headers.

![image](https://user-images.githubusercontent.com/1675868/58577611-d5d56680-8214-11e9-9ac6-96ec8f814868.png)

I asked for the export of the screen so we can repro but that produced an error. If this error is unrelated to their piece of work make a new ticket for that.

![image](https://user-images.githubusercontent.com/1675868/58577583-cbb36800-8214-11e9-9e91-008add1a3d3b.png)

[pet_adoption (1).spark.txt](https://github.com/ProcessMaker/spark-screen-builder/files/3233670/pet_adoption.1.spark.txt)

**Comment by velkymx** [comment]
[Vue warn]: Unknown custom element: <FormMultiColumn> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

found in

---> <VueFormRenderer>
       <TaskScreen> at resources/js/tasks/components/TaskForm.vue
         <Root>

**Comment by ssshake** [comment]
![image](https://user-images.githubusercontent.com/1675868/58586109-58b3ec80-8228-11e9-9559-93090625eeb8.png)
