### ISSUE TITLE
Rich Text variables not working

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/spark-screen-builder#226]
{{mustache}} fields are not displayed properly from Rich Text. This was working in the previous release.

![image](https://user-images.githubusercontent.com/535300/58995583-a2ad4d00-87a9-11e9-9680-97cb9c0ac3f8.png)

**Comment by PMQABen** [comment]
Did some tinkering on my local machine running 5.1. If I put a Rich Text control that contains the variable inside a Table control, it displays correctly. If I have it outside the table, it shows up as `{{variable}}`
