### ISSUE TITLE
Losing State

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/spark-screen-builder#233]
Steps to Reproduce:

Go to a form with a checkbox

Turn on the style and the checked state

Save and update the app

**Current Behavior:**

The state and style resets in the inspector

![image](https://user-images.githubusercontent.com/535300/59141203-881bd500-895d-11e9-8a8f-4361ee41ee92.png)

 

**Expected Behavior:**

The state and style stays as the user left them

**Comment by tuantruong625** [comment]
Changes were required in vue form elements repo.
The form check component, was missing a prop of `checked`
PR (https://github.com/ProcessMaker/vue-form-elements/pull/44) for the fix.
